# Generated by Django 5.1.2 on 2024-10-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lists_of_order',
        ),
    ]
