# Generated by Django 5.1.2 on 2024-10-27 14:55

import gardensets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_status', '0002_delete_lists_of_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists_refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('email', models.EmailField(default='', max_length=254)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('order_to_be_cancelled', models.TextField(default='', verbose_name=gardensets.models.Gardenset)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('refund_status', models.BooleanField(default=False)),
                ('refund_number', models.CharField(editable=False, max_length=32)),
            ],
        ),
    ]
