# Generated by Django 5.1.2 on 2024-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists_refund',
            name='order_to_be_cancelled',
        ),
        migrations.AddField(
            model_name='lists_refund',
            name='canceled_order',
            field=models.BooleanField(default=False),
        ),
    ]
