# Generated by Django 5.1.2 on 2024-10-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_lists_order'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
