# Generated by Django 5.1.2 on 2024-10-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_lists_order_user_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_order',
            name='order_to_be_delivered',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lists_order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_number', to='profiles.userprofile'),
        ),
    ]
