# Generated by Django 5.1.2 on 2024-10-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_lists_order_order_to_be_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='lists_order',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
