# Generated by Django 5.1.2 on 2024-10-27 13:12

import gardensets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_lists_order_email_lists_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_order',
            name='tracking_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lists_order',
            name='order_to_be_delivered',
            field=models.TextField(default='', verbose_name=gardensets.models.Gardenset),
        ),
    ]
