# Generated by Django 5.1.2 on 2024-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_lists_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists_order',
            name='canceled_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lists_order',
            name='returned_status',
            field=models.BooleanField(default=False),
        ),
    ]
