# Generated by Django 5.1.2 on 2024-10-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardensets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
